services:
  gibassets-postgres-rw:
    container_name: gibassets-postgres-rw
    # image: postgres:16
    build:
      context: .
      dockerfile: Dockerfile.postgres
    shm_size: 16g
    command: postgres -c /usr/share/postgresql/postgresql.conf
    ports:
      - 5876:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./postgresql.conf:/usr/share/postgresql/postgresql.conf
    networks:
      - gibassets
    environment:
      - POSTGRES_DB=gibassets
      - POSTGRES_USER=gibassets
      - POSTGRES_PASSWORD=password
  gibassets-postgres-migrate:
    container_name: gibassets-postgres-migrate
    image: registry.gitlab.com/pulsechaincom/gibassets:latest
    command: sh -cx "npm run db:migrate-latest && npm run db:seed"
    networks:
      - gibassets
    environment:
      DEBUG: "${DEBUG:-📷*}"
      DATABASE_URL: "${DATABASE_URL:-postgres://gibassets:password@gibassets-postgres-rw:5432/gibassets}"

networks:
  gibassets:
    driver: bridge

volumes:
  gibassets:
    external: true
