services:
  gibassets-postgres:
    container_name: gibassets-postgres
    # image: postgres:13
    build:
      context: .
      dockerfile: Dockerfile.postgres
    shm_size: 16g
    command: ['postgres']
    ports:
      - 5876:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - gibassets
    environment:
      - POSTGRES_DB=gibassets
      - POSTGRES_USER=gibassets
      - POSTGRES_PASSWORD=password
  gibassets-postgres-migrate:
    container_name: gibassets-postgres-migrate
    image: gibsfinance/assets:latest
    command: sh -cx "bun run db:migrate-latest && bun run db:seed"
    networks:
      - gibassets
    environment:
      DEBUG: '${DEBUG:-📷*}'
      DATABASE_URL: 'postgres://gibassets:password@gibassets-postgres:5432/gibassets'
  gibassets-collect:
    container_name: gibassets-collect
    build:
      context: .
      dockerfile: Dockerfile.worker
    command: ['bun', 'run', 'collect']
    volumes:
      - ./missing:/usr/src/app/missing
      - ./src:/usr/src/app/src
    depends_on:
      - gibassets-postgres
    networks:
      - gibassets
    environment:
      DATABASE_URL: 'postgres://gibassets:password@gibassets-postgres:5432/gibassets'
      FAKE_SPINNER: 'true'
      RPC_56: $RPC_56
  gibassets-server:
    depends_on:
      - gibassets-postgres
    container_name: gibassets-server
    build:
      context: .
      dockerfile: Dockerfile
    command: ['bun', 'run', 'server']
    volumes:
      - ./src:/usr/src/app/src
    networks:
      - gibassets
    environment:
      ROOT_URI: 'http://localhost:3456'
      DATABASE_URL: 'postgres://gibassets:password@gibassets-postgres:5432/gibassets'
      RPC_56: $RPC_56
    ports:
      - 3456:3000

networks:
  gibassets:
    driver: bridge

volumes:
  gibassets:
    external: true
