-- Deduplicate token rows where (network_id, citext provided_id) collides.
-- Cause: the token_id trigger hashed `network_id::text || provided_id::text`, which
-- preserves case even though provided_id is citext. Tokens inserted with different
-- casing (e.g. "0xABC" vs "0xabc") produced different token_ids but are equal under
-- citext comparison, causing stats/token list mismatches. Fix: normalize case in the
-- hash, collapse duplicates, and add a uniqueness guarantee.

-- 1. Map duplicate token rows to a single winner (the one with most list_token refs,
--    tie-broken by token_id). Subsequent DELETE/UPDATE steps reference this table.
CREATE TEMPORARY TABLE _token_dedup AS
WITH ranked AS (
  SELECT
    t.token_id,
    t.network_id,
    t.provided_id,
    ROW_NUMBER() OVER (
      PARTITION BY t.network_id, t.provided_id
      ORDER BY (
        SELECT count(*) FROM list_token lt WHERE lt.token_id = t.token_id
      ) DESC,
      t.token_id ASC
    ) AS rn
  FROM token t
)
SELECT
  loser.token_id AS loser_id,
  winner.token_id AS winner_id
FROM ranked loser
INNER JOIN ranked winner
  ON winner.network_id = loser.network_id
 AND winner.provided_id = loser.provided_id
 AND winner.rn = 1
WHERE loser.rn > 1;--> statement-breakpoint

-- 2a. Drop loser list_tokens that would collide with an existing winner list_token.
--     list_token_id = keccak(token_id || list_id), so reparenting a loser to a winner
--     already present in the same list produces a PK conflict. Winner's row wins.
DELETE FROM list_token
WHERE list_token_id IN (
  SELECT lt.list_token_id FROM list_token lt
  INNER JOIN _token_dedup m ON m.loser_id = lt.token_id
  WHERE EXISTS (
    SELECT 1 FROM list_token winner_lt
    WHERE winner_lt.token_id = m.winner_id
      AND winner_lt.list_id = lt.list_id
  )
);--> statement-breakpoint

-- 2b. Reparent remaining list_token rows from losers to winners. The list_token_id
--     PK will be regenerated by the BEFORE-UPDATE trigger since we're touching token_id.
UPDATE list_token SET token_id = m.winner_id
FROM _token_dedup m
WHERE list_token.token_id = m.loser_id;--> statement-breakpoint

-- 3. Reparent bridge_link rows. Native and bridged sides are handled separately.
UPDATE bridge_link SET native_token_id = m.winner_id
FROM _token_dedup m
WHERE bridge_link.native_token_id = m.loser_id;--> statement-breakpoint

UPDATE bridge_link SET bridged_token_id = m.winner_id
FROM _token_dedup m
WHERE bridge_link.bridged_token_id = m.loser_id;--> statement-breakpoint

-- 4. Delete the loser token rows. Cascades fire on any stragglers (should be none).
DELETE FROM token
WHERE token_id IN (SELECT loser_id FROM _token_dedup);--> statement-breakpoint

DROP TABLE _token_dedup;--> statement-breakpoint

-- 5. Update the trigger to lowercase provided_id before hashing. This ensures that
--    future inserts with different casing resolve to the same token_id, so the
--    onConflictDoUpdate upsert in insertToken dedupes correctly.
CREATE OR REPLACE FUNCTION public.gcid_token_token_id_networkid_providedid()
  RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.token_id := keccak256(NEW.network_id::text || lower(NEW.provided_id::text));
  RETURN NEW;
END;
$$;--> statement-breakpoint

-- 6. Add unique constraint on (network_id, provided_id). Enforced by citext, this
--    prevents future case-only duplicates regardless of trigger logic. Wrapped in
--    a DO block so re-running the migration against an already-fixed database is
--    a no-op rather than an error.
DO $do$ BEGIN
  ALTER TABLE token ADD CONSTRAINT token_network_provided_unique UNIQUE (network_id, provided_id);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL;
END $do$;
