-- Deduplicate token rows where (network_id, citext provided_id) collides.
-- Cause: the token_id trigger hashed `network_id::text || provided_id::text`, which
-- preserves case even though provided_id is citext. Tokens inserted with different
-- casing (e.g. "0xABC" vs "0xabc") produced different token_ids but are equal under
-- citext comparison, causing stats/token list mismatches. Fix: normalize case in the
-- hash, collapse duplicates, and add a uniqueness guarantee.

-- 1. Map duplicate token rows to a single winner (the one with most list_token refs,
--    tie-broken by token_id). Subsequent DELETE/UPDATE steps reference this table.
CREATE TEMPORARY TABLE _token_dedup AS
WITH ranked AS (
  SELECT
    t.token_id,
    t.network_id,
    t.provided_id,
    ROW_NUMBER() OVER (
      PARTITION BY t.network_id, t.provided_id
      ORDER BY (
        SELECT count(*) FROM list_token lt WHERE lt.token_id = t.token_id
      ) DESC,
      t.token_id ASC
    ) AS rn
  FROM token t
)
SELECT
  loser.token_id AS loser_id,
  winner.token_id AS winner_id
FROM ranked loser
INNER JOIN ranked winner
  ON winner.network_id = loser.network_id
 AND winner.provided_id = loser.provided_id
 AND winner.rn = 1
WHERE loser.rn > 1;--> statement-breakpoint

-- 2a. Drop loser list_tokens that would collide with an existing winner list_token.
--     list_token_id = keccak(token_id || list_id), so reparenting a loser to a winner
--     already present in the same list produces a PK conflict. Winner's row wins.
DELETE FROM list_token
WHERE list_token_id IN (
  SELECT lt.list_token_id FROM list_token lt
  INNER JOIN _token_dedup m ON m.loser_id = lt.token_id
  WHERE EXISTS (
    SELECT 1 FROM list_token winner_lt
    WHERE winner_lt.token_id = m.winner_id
      AND winner_lt.list_id = lt.list_id
  )
);--> statement-breakpoint

-- 2b. Two or more losers in the same list can map to the same winner (3+ case variants
--     with the winner absent from that list). The BEFORE-UPDATE trigger regenerates
--     list_token_id = keccak256(token_id || list_id), so reparenting both would produce
--     the same PK. Keep one row per post-reparent (winner_id, list_id) identity. (Rows
--     colliding with a winner-attached row were already removed in 2a, so ranking among
--     loser rows by list_token_id is a deterministic, sufficient tie-break.)
DELETE FROM list_token
WHERE list_token_id IN (
  SELECT list_token_id FROM (
    SELECT lt.list_token_id,
           ROW_NUMBER() OVER (
             PARTITION BY m.winner_id, lt.list_id
             ORDER BY lt.list_token_id
           ) AS rn
    FROM list_token lt
    INNER JOIN _token_dedup m ON m.loser_id = lt.token_id
  ) candidates
  WHERE candidates.rn > 1
);--> statement-breakpoint

-- 2c. Reparent remaining list_token rows from losers to winners. The list_token_id
--     PK will be regenerated by the BEFORE-UPDATE trigger since we're touching token_id.
UPDATE list_token SET token_id = m.winner_id
FROM _token_dedup m
WHERE list_token.token_id = m.loser_id;--> statement-breakpoint

-- 3a. Guard bridge_link reparenting. bridge_link_id = keccak256(native_token_id ||
--     bridged_token_id || bridge_id) is regenerated by a BEFORE-UPDATE trigger, and
--     BOTH token columns may be remapped. Compute each row's FINAL post-reparent
--     identity (winner mapping applied to both sides), rank rows within each
--     (bridge_id, final native, final bridged) group preferring a row that already
--     needs no change (so its other columns are preserved), and drop the rest.
DELETE FROM bridge_link
WHERE bridge_link_id IN (
  SELECT bridge_link_id FROM (
    SELECT bl.bridge_link_id,
           ROW_NUMBER() OVER (
             PARTITION BY bl.bridge_id,
               COALESCE(mn.winner_id, bl.native_token_id),
               COALESCE(mb.winner_id, bl.bridged_token_id)
             ORDER BY (mn.winner_id IS NULL AND mb.winner_id IS NULL) DESC,
                      bl.bridge_link_id
           ) AS rn
    FROM bridge_link bl
    LEFT JOIN _token_dedup mn ON mn.loser_id = bl.native_token_id
    LEFT JOIN _token_dedup mb ON mb.loser_id = bl.bridged_token_id
  ) candidates
  WHERE candidates.rn > 1
);--> statement-breakpoint

-- 3b. Reparent both sides in a single UPDATE so the trigger regenerates bridge_link_id
--     exactly once, with the final identity guaranteed unique by 3a. (Updating the two
--     columns in separate statements would pass through intermediate identities that
--     the guard does not cover.)
UPDATE bridge_link SET
  native_token_id = COALESCE(m.native_winner, bridge_link.native_token_id),
  bridged_token_id = COALESCE(m.bridged_winner, bridge_link.bridged_token_id)
FROM (
  SELECT bl.bridge_link_id,
         mn.winner_id AS native_winner,
         mb.winner_id AS bridged_winner
  FROM bridge_link bl
  LEFT JOIN _token_dedup mn ON mn.loser_id = bl.native_token_id
  LEFT JOIN _token_dedup mb ON mb.loser_id = bl.bridged_token_id
  WHERE mn.loser_id IS NOT NULL OR mb.loser_id IS NOT NULL
) m
WHERE bridge_link.bridge_link_id = m.bridge_link_id;--> statement-breakpoint

-- 4. Delete the loser token rows. Cascades fire on any stragglers (should be none).
DELETE FROM token
WHERE token_id IN (SELECT loser_id FROM _token_dedup);--> statement-breakpoint

DROP TABLE _token_dedup;--> statement-breakpoint

-- 5. Update the trigger to lowercase provided_id before hashing. This ensures that
--    future inserts with different casing resolve to the same token_id, so the
--    onConflictDoUpdate upsert in insertToken dedupes correctly.
CREATE OR REPLACE FUNCTION public.gcid_token_token_id_networkid_providedid()
  RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.token_id := keccak256(NEW.network_id::text || lower(NEW.provided_id::text));
  RETURN NEW;
END;
$$;--> statement-breakpoint

-- 6. Add unique constraint on (network_id, provided_id). Enforced by citext, this
--    prevents future case-only duplicates regardless of trigger logic. Wrapped in
--    a DO block so re-running the migration against an already-fixed database is
--    a no-op rather than an error.
DO $do$ BEGIN
  ALTER TABLE token ADD CONSTRAINT token_network_provided_unique UNIQUE (network_id, provided_id);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL;
END $do$;
