name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'yarn'
      - run: corepack enable
      - run: yarn install --immutable
      # start the docker database
      # start node server
      - run: yarn run build
      - run: docker compose build
      - run: docker compose up -d postgres collect server
      - run: sleep 3
      - run: yarn run test
