name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node_version: 20
      - run: npm install -g pnpm
      - run: pnpm install
      # start the docker database
      # start node server
      - run: docker compose buildact
      - run: docker compose up -d gibassets-postgres gibassets-collect gibassets-server
      - run: sleep 30
      - run: pnpm test
